version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    restart:
      always
    depends_on:
      - db
    environment:
      DOCKER_ENV: 1

  db:
    image: mysql:latest
    ports:
      - "1234:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Database:/docker-entrypoint-initdb.d/:ro